id = "taskfile"
name = "Taskfile"
description = "Taskfile syntax highlighting and task runner support"
version = "0.1.0"
schema_version = 1
authors = ["Nick Glu <nick@nickalie.com>"]
repository = "https://github.com/nickalie/zed-taskfile"
